project_id = "izrmteohhqlycqydafhq"

[functions.ai-insights]
verify_jwt = false

[functions.parent-portal-access]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.chunked-upload]
verify_jwt = false

[functions.process-dataset]
verify_jwt = false
